import Head from 'next/head'
import { Coda, Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useReducer, useState } from 'react'
import Products from '@/utils/data'
import Navbar from '@/components/Navbar'
import { InitialState, cartfunction } from '@/utils/Store'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  const [state, dispatch] = useReducer(cartfunction, InitialState)

  const AddToCart = (requestObject) => {

    // first check for the item if already in cart
    const AlreadyInCart = state.cart.cartItems.find((x)=>x.slug === requestObject.slug)

    // see what quantity to set , if existing, increase 1 or set to 1 for new object
    const RequestQuantity = AlreadyInCart ? AlreadyInCart.quantity + 1 : 1;

    // now send dispatch

    dispatch({
      type : "Add_To_Cart",
      payload : {
        ...requestObject,
        quantity : RequestQuantity,
      }
    })

  }


  useEffect(() => {
    console.log('Cart state:', JSON.stringify(state.cart));
  }, [state.cart]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Navbar />
      </Head>
      <main className={styles.main}>
        {/* Code for cards */}
        {Products.map((x) => (
          <div className="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
              <img className="rounded-t-lg" src={x.image} alt="" />
            </a>
            <div className="p-5">
              <a href="#">
                <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{x.name}</h5>
              </a>
              <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">Price : {x.price}</p>
              <a onClick={() => AddToCart(x)} href="#" className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Add to Cart
                <svg className="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9" />
                </svg>
              </a>
            </div>
          </div>
        ))}
      </main>
    </>
  )
}
